version: '3.9'

services:
  api:
    image: ghcr.io/0-5788719150923125/ctx:latest
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    volumes:
      - ./index.js:/src/index.js
    network_mode: host
    environment:
      WEBUI: enabled
      ANONYMOUS: 'false'
    ports:
      - 9668:9666
