FROM arm64v8/node:18-bookworm

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl \
    git \
    openssh-client \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY package*.json *.js ./

RUN npm install --production

CMD ["node", "index.js"]

LABEL MAINTAINER="R"
