version: '3.9'

services:
  ctx:
    image: ghcr.io/0-5788719150923125/ctx:latest
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    volumes:
      - ./index.js:/src/index.js
    environment:
      WEBUI: enabled
      ANONYMOUS: 'true'
    ports:
      - 9668:9666
